name: clone workflow
on:
  workflow_dispatch:
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
    - name: testing 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd ../pub
            rm -r -f CMSC389T-Web-Template