name: update workflow
on:
  [workflow_dispatch,push]
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
    - name: testing 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd ../pub
            git pull git@github.com:Jozue124/CMSC389T-Web-Template.git